package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IdGen generated by hbm2java
 */
@Entity
@Table(name="id_gen")
public class IdGen  implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String genKey;
     private Long genValue;

    public IdGen() {
    }

	
    public IdGen(String genKey) {
        this.genKey = genKey;
    }
    public IdGen(String genKey, Long genValue) {
       this.genKey = genKey;
       this.genValue = genValue;
    }
   
    @Id 
    @Column(name="GEN_KEY", unique=true, nullable=false)
    public String getGenKey() {
        return this.genKey;
    }
    
    public void setGenKey(String genKey) {
        this.genKey = genKey;
    }

    
    @Column(name="GEN_VALUE")
    public Long getGenValue() {
        return this.genValue;
    }
    
    public void setGenValue(Long genValue) {
        this.genValue = genValue;
    }




}


