package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InventoryTransactionTypes generated by hbm2java
 */
@Entity
@Table(name="inventory_transaction_types")
public class InventoryTransactionTypes  implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long id;
     private Date createDate;
     private String createUser;
     private String typeName;
     private Date updateDate;
     private List<InventoryTransactions> inventoryTransactionses = new ArrayList<InventoryTransactions>(0);

    public InventoryTransactionTypes() {
    }

	
    public InventoryTransactionTypes(long id) {
        this.id = id;
    }
    public InventoryTransactionTypes(long id, Date createDate, String createUser, String typeName, Date updateDate, List<InventoryTransactions> inventoryTransactionses) {
       this.id = id;
       this.createDate = createDate;
       this.createUser = createUser;
       this.typeName = typeName;
       this.updateDate = updateDate;
       this.inventoryTransactionses = inventoryTransactionses;
    }
   
    @TableGenerator(
            name="SSMGen", 
            table="ID_GEN", 
            pkColumnName="GEN_KEY", 
            valueColumnName="GEN_VALUE", 
            pkColumnValue="INVENTORYTRANSACTIONTYPE_ID", 
            allocationSize=1)
    @Id 
    @Column(name="id")
    @GeneratedValue(strategy=GenerationType.TABLE, generator="SSMGen")
    public long getId() {
        return this.id;
    }
    
    public void ListId(long id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void ListCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}


	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}


	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}


	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}


	public void setInventoryTransactionses(List<InventoryTransactions> inventoryTransactionses) {
		this.inventoryTransactionses = inventoryTransactionses;
	}


	@Column(name="create_user")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void ListCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="type_name")
    public String getTypeName() {
        return this.typeName;
    }
    
    public void ListTypeName(String typeName) {
        this.typeName = typeName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void ListUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="inventoryTransactionTypes")
    public List<InventoryTransactions> getInventoryTransactionses() {
        return this.inventoryTransactionses;
    }
    
    public void ListInventoryTransactionses(List<InventoryTransactions> inventoryTransactionses) {
        this.inventoryTransactionses = inventoryTransactionses;
    }


	public void setId(long id) {
		this.id = id;
	}




}


