package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invoices generated by hbm2java
 */
@Entity
@Table(name="invoices")
public class Invoices  implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long id;
     private Orders orders;
     private BigDecimal amountDue;
     private Date createDate;
     private String createUser;
     private Date dueDate;
     private Date invoiceDate;
     private BigDecimal shipping;
     private BigDecimal tax;
     private Date updateDate;

    public Invoices() {
    }

	
    public Invoices(long id) {
        this.id = id;
    }
    public Invoices(long id, Orders orders, BigDecimal amountDue, Date createDate, String createUser, Date dueDate, Date invoiceDate, BigDecimal shipping, BigDecimal tax, Date updateDate) {
       this.id = id;
       this.orders = orders;
       this.amountDue = amountDue;
       this.createDate = createDate;
       this.createUser = createUser;
       this.dueDate = dueDate;
       this.invoiceDate = invoiceDate;
       this.shipping = shipping;
       this.tax = tax;
       this.updateDate = updateDate;
    }
   
    @TableGenerator(
            name="SSMGen", 
            table="ID_GEN", 
            pkColumnName="GEN_KEY", 
            valueColumnName="GEN_VALUE", 
            pkColumnValue="INVOICE_ID", 
            allocationSize=1)
    @Id 
    @Column(name="id")
    @GeneratedValue(strategy=GenerationType.TABLE, generator="SSMGen")
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id")
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    
    @Column(name="amount_due")
    public BigDecimal getAmountDue() {
        return this.amountDue;
    }
    
    public void setAmountDue(BigDecimal amountDue) {
        this.amountDue = amountDue;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="create_user")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="due_date", length=19)
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="invoice_date", length=19)
    public Date getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    
    @Column(name="shipping")
    public BigDecimal getShipping() {
        return this.shipping;
    }
    
    public void setShipping(BigDecimal shipping) {
        this.shipping = shipping;
    }

    
    @Column(name="tax")
    public BigDecimal getTax() {
        return this.tax;
    }
    
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


