package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrdersOrdersStatus generated by hbm2java
 */
@Entity
@Table(name="orders_orders_status"
    ,catalog="ssm_test"
)
public class OrdersOrdersStatus  implements java.io.Serializable {


     private OrdersOrdersStatusId id;
     private Orders orders;
     private OrdersStatus ordersStatus;

    public OrdersOrdersStatus() {
    }

    public OrdersOrdersStatus(OrdersOrdersStatusId id, Orders orders, OrdersStatus ordersStatus) {
       this.id = id;
       this.orders = orders;
       this.ordersStatus = ordersStatus;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orderId", column=@Column(name="Order_id", nullable=false) ), 
        @AttributeOverride(name="orderStatussId", column=@Column(name="orderStatuss_id", nullable=false) ) } )
    public OrdersOrdersStatusId getId() {
        return this.id;
    }
    
    public void setId(OrdersOrdersStatusId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Order_id", nullable=false, insertable=false, updatable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="orderStatuss_id", nullable=false, insertable=false, updatable=false)
    public OrdersStatus getOrdersStatus() {
        return this.ordersStatus;
    }
    
    public void setOrdersStatus(OrdersStatus ordersStatus) {
        this.ordersStatus = ordersStatus;
    }




}


