package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders")
public class Orders  implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long id;
     private Customer customer;
     private Employees employees;
     private OrdersTaxStatus ordersTaxStatus;
     private Shippers shippers;
     private Date createDate;
     private String createUser;
     private Long currentStatus;
     private String notes;
     private Date orderDate;
     private Date paidDate;
     private String paymentType;
     private String qty;
     private String recipe;
     private String shipAddress;
     private String shipCity;
     private String shipCountryRegion;
     private String shipName;
     private String shipStateProvince;
     private String shipZipPostalCode;
     private Date shippedDate;
     private BigDecimal shippingFee;
     private Double taxRate;
     private BigDecimal taxes;
     private Date updateDate;
     private List<XtblDocket> xtblDockets = new ArrayList<XtblDocket>(0);
     private List<InventoryTransactions> inventoryTransactionses = new ArrayList<InventoryTransactions>(0);
     private List<OrdersOrdersStatus> ordersOrdersStatuses = new ArrayList<OrdersOrdersStatus>(0);
     private List<OrderDetails> orderDetailses = new ArrayList<OrderDetails>(0);
     private List<OrdersStatusOrders> ordersStatusOrderses = new ArrayList<OrdersStatusOrders>(0);
     private List<Invoices> invoiceses = new ArrayList<Invoices>(0);
     private List<OrdersTaxStatus> ordersTaxStatuses = new ArrayList<OrdersTaxStatus>(0);
     
     

    public Orders() {
    }

	
    public Orders(long id) {
        this.id = id;
    }
    
    public Orders(long id, Customer customer, Employees employees, OrdersTaxStatus ordersTaxStatus, Shippers shippers, Date createDate, String createUser, Long currentStatus, String notes, Date orderDate, Date paidDate, String paymentType, String qty, String recipe, String shipAddress, String shipCity, String shipCountryRegion, String shipName, String shipStateProvince, String shipZipPostalCode, Date shippedDate, BigDecimal shippingFee, Double taxRate, BigDecimal taxes, Date updateDate, List<XtblDocket> xtblDockets, List<InventoryTransactions> inventoryTransactionses, List<OrdersOrdersStatus> ordersOrdersStatuses, List<OrderDetails> orderDetailses, List<OrdersStatusOrders> ordersStatusOrderses, List<Invoices> invoiceses, List<OrdersTaxStatus> ordersTaxStatuses) {
       this.id = id;
       this.customer = customer;
       this.employees = employees;
       this.ordersTaxStatus = ordersTaxStatus;
       this.shippers = shippers;
       this.createDate = createDate;
       this.createUser = createUser;
       this.currentStatus = currentStatus;
       this.notes = notes;
       this.orderDate = orderDate;
       this.paidDate = paidDate;
       this.paymentType = paymentType;
       this.qty = qty;
       this.recipe = recipe;
       this.shipAddress = shipAddress;
       this.shipCity = shipCity;
       this.shipCountryRegion = shipCountryRegion;
       this.shipName = shipName;
       this.shipStateProvince = shipStateProvince;
       this.shipZipPostalCode = shipZipPostalCode;
       this.shippedDate = shippedDate;
       this.shippingFee = shippingFee;
       this.taxRate = taxRate;
       this.taxes = taxes;
       this.updateDate = updateDate;
       this.xtblDockets = xtblDockets;
       this.inventoryTransactionses = inventoryTransactionses;
       this.ordersOrdersStatuses = ordersOrdersStatuses;
       this.orderDetailses = orderDetailses;
       this.ordersStatusOrderses = ordersStatusOrderses;
       this.invoiceses = invoiceses;
       this.ordersTaxStatuses = ordersTaxStatuses;
    }
   
    @TableGenerator(
            name="SSMGen", 
            table="ID_GEN", 
            pkColumnName="GEN_KEY", 
            valueColumnName="GEN_VALUE", 
            pkColumnValue="ORDER_ID", 
            allocationSize=1)
    @Id 
    @Column(name="id")
    @GeneratedValue(strategy=GenerationType.TABLE, generator="SSMGen")
    public long getId() {
        return this.id;
    }
    
    public void ListId(long id) {
        this.id = id;
    }

public void setCustomer(Customer customer) {
		this.customer = customer;
	}


	public void setEmployees(Employees employees) {
		this.employees = employees;
	}


	public void setOrdersTaxStatus(OrdersTaxStatus ordersTaxStatus) {
		this.ordersTaxStatus = ordersTaxStatus;
	}


	public void setShippers(Shippers shippers) {
		this.shippers = shippers;
	}


	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}


	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}


	public void setCurrentStatus(Long currentStatus) {
		this.currentStatus = currentStatus;
	}


	public void setNotes(String notes) {
		this.notes = notes;
	}


	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}


	public void setPaidDate(Date paidDate) {
		this.paidDate = paidDate;
	}


	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}


	public void setQty(String qty) {
		this.qty = qty;
	}


	public void setRecipe(String recipe) {
		this.recipe = recipe;
	}


	public void setShipAddress(String shipAddress) {
		this.shipAddress = shipAddress;
	}


	public void setShipCity(String shipCity) {
		this.shipCity = shipCity;
	}


	public void setShipCountryRegion(String shipCountryRegion) {
		this.shipCountryRegion = shipCountryRegion;
	}


	public void setShipName(String shipName) {
		this.shipName = shipName;
	}


	public void setShipStateProvince(String shipStateProvince) {
		this.shipStateProvince = shipStateProvince;
	}


	public void setShipZipPostalCode(String shipZipPostalCode) {
		this.shipZipPostalCode = shipZipPostalCode;
	}


	public void setShippedDate(Date shippedDate) {
		this.shippedDate = shippedDate;
	}


	public void setShippingFee(BigDecimal shippingFee) {
		this.shippingFee = shippingFee;
	}


	public void setTaxRate(Double taxRate) {
		this.taxRate = taxRate;
	}


	public void setTaxes(BigDecimal taxes) {
		this.taxes = taxes;
	}


	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}


	public void setXtblDockets(List<XtblDocket> xtblDockets) {
		this.xtblDockets = xtblDockets;
	}


	public void setInventoryTransactionses(List<InventoryTransactions> inventoryTransactionses) {
		this.inventoryTransactionses = inventoryTransactionses;
	}


	public void setOrdersOrdersStatuses(List<OrdersOrdersStatus> ordersOrdersStatuses) {
		this.ordersOrdersStatuses = ordersOrdersStatuses;
	}


	public void setOrderDetailses(List<OrderDetails> orderDetailses) {
		this.orderDetailses = orderDetailses;
	}


	public void setOrdersStatusOrderses(List<OrdersStatusOrders> ordersStatusOrderses) {
		this.ordersStatusOrderses = ordersStatusOrderses;
	}


	public void setInvoiceses(List<Invoices> invoiceses) {
		this.invoiceses = invoiceses;
	}


	public void setOrdersTaxStatuses(List<OrdersTaxStatus> ordersTaxStatuses) {
		this.ordersTaxStatuses = ordersTaxStatuses;
	}


@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id")
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void ListCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id")
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void ListEmployees(Employees employees) {
        this.employees = employees;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tax_status_id")
    public OrdersTaxStatus getOrdersTaxStatus() {
        return this.ordersTaxStatus;
    }
    
    public void ListOrdersTaxStatus(OrdersTaxStatus ordersTaxStatus) {
        this.ordersTaxStatus = ordersTaxStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="shipper_id")
    public Shippers getShippers() {
        return this.shippers;
    }
    
    public void ListShippers(Shippers shippers) {
        this.shippers = shippers;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void ListCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="create_user")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void ListCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="current_status")
    public Long getCurrentStatus() {
        return this.currentStatus;
    }
    
    public void ListCurrentStatus(Long currentStatus) {
        this.currentStatus = currentStatus;
    }

    
    @Column(name="notes")
    public String getNotes() {
        return this.notes;
    }
    
    public void ListNotes(String notes) {
        this.notes = notes;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="order_date", length=19)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void ListOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="paid_date", length=19)
    public Date getPaidDate() {
        return this.paidDate;
    }
    
    public void ListPaidDate(Date paidDate) {
        this.paidDate = paidDate;
    }

    
    @Column(name="payment_type")
    public String getPaymentType() {
        return this.paymentType;
    }
    
    public void ListPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    
    @Column(name="qty")
    public String getQty() {
        return this.qty;
    }
    
    public void ListQty(String qty) {
        this.qty = qty;
    }

    
    @Column(name="recipe")
    public String getRecipe() {
        return this.recipe;
    }
    
    public void ListRecipe(String recipe) {
        this.recipe = recipe;
    }

    
    @Column(name="ship_address")
    public String getShipAddress() {
        return this.shipAddress;
    }
    
    public void ListShipAddress(String shipAddress) {
        this.shipAddress = shipAddress;
    }

    
    @Column(name="ship_city")
    public String getShipCity() {
        return this.shipCity;
    }
    
    public void ListShipCity(String shipCity) {
        this.shipCity = shipCity;
    }

    
    @Column(name="ship_country_region")
    public String getShipCountryRegion() {
        return this.shipCountryRegion;
    }
    
    public void ListShipCountryRegion(String shipCountryRegion) {
        this.shipCountryRegion = shipCountryRegion;
    }

    
    @Column(name="ship_name")
    public String getShipName() {
        return this.shipName;
    }
    
    public void ListShipName(String shipName) {
        this.shipName = shipName;
    }

    
    @Column(name="ship_state_province")
    public String getShipStateProvince() {
        return this.shipStateProvince;
    }
    
    public void ListShipStateProvince(String shipStateProvince) {
        this.shipStateProvince = shipStateProvince;
    }

    
    @Column(name="ship_zip_postal_code")
    public String getShipZipPostalCode() {
        return this.shipZipPostalCode;
    }
    
    public void ListShipZipPostalCode(String shipZipPostalCode) {
        this.shipZipPostalCode = shipZipPostalCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="shipped_date", length=19)
    public Date getShippedDate() {
        return this.shippedDate;
    }
    
    public void ListShippedDate(Date shippedDate) {
        this.shippedDate = shippedDate;
    }

    
    @Column(name="shipping_fee")
    public BigDecimal getShippingFee() {
        return this.shippingFee;
    }
    
    public void ListShippingFee(BigDecimal shippingFee) {
        this.shippingFee = shippingFee;
    }

    
    @Column(name="tax_rate", precision=22, scale=0)
    public Double getTaxRate() {
        return this.taxRate;
    }
    
    public void ListTaxRate(Double taxRate) {
        this.taxRate = taxRate;
    }

    
    @Column(name="taxes")
    public BigDecimal getTaxes() {
        return this.taxes;
    }
    
    public void ListTaxes(BigDecimal taxes) {
        this.taxes = taxes;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void ListUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public List<XtblDocket> getXtblDockets() {
        return this.xtblDockets;
    }
    
    public void ListXtblDockets(List<XtblDocket> xtblDockets) {
        this.xtblDockets = xtblDockets;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public List<InventoryTransactions> getInventoryTransactionses() {
        return this.inventoryTransactionses;
    }
    
    public void ListInventoryTransactionses(List<InventoryTransactions> inventoryTransactionses) {
        this.inventoryTransactionses = inventoryTransactionses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public List<OrdersOrdersStatus> getOrdersOrdersStatuses() {
        return this.ordersOrdersStatuses;
    }
    
    public void ListOrdersOrdersStatuses(List<OrdersOrdersStatus> ordersOrdersStatuses) {
        this.ordersOrdersStatuses = ordersOrdersStatuses;
    }
    
@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public List<OrderDetails> getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void ListOrderDetailses(List<OrderDetails> orderDetailses) {
        this.orderDetailses = orderDetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public List<OrdersStatusOrders> getOrdersStatusOrderses() {
        return this.ordersStatusOrderses;
    }
    
    public void ListOrdersStatusOrderses(List<OrdersStatusOrders> ordersStatusOrderses) {
        this.ordersStatusOrderses = ordersStatusOrderses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public List<Invoices> getInvoiceses() {
        return this.invoiceses;
    }
    
    public void ListInvoiceses(List<Invoices> invoiceses) {
        this.invoiceses = invoiceses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public List<OrdersTaxStatus> getOrdersTaxStatuses() {
        return this.ordersTaxStatuses;
    }
    
    public void ListOrdersTaxStatuses(List<OrdersTaxStatus> ordersTaxStatuses) {
        this.ordersTaxStatuses = ordersTaxStatuses;
    }


	public void setId(long id) {
		this.id = id;
	}




}


