package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrdersStatusOrders generated by hbm2java
 */
@Entity
@Table(name="orders_status_orders"
    ,catalog="ssm_test"
)
public class OrdersStatusOrders  implements java.io.Serializable {


     private OrdersStatusOrdersId id;
     private Orders orders;
     private OrdersStatus ordersStatus;

    public OrdersStatusOrders() {
    }

    public OrdersStatusOrders(OrdersStatusOrdersId id, Orders orders, OrdersStatus ordersStatus) {
       this.id = id;
       this.orders = orders;
       this.ordersStatus = ordersStatus;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="ordersStatusId", column=@Column(name="OrdersStatus_id", nullable=false) ), 
        @AttributeOverride(name="ordersId", column=@Column(name="orders_id", nullable=false) ) } )
    public OrdersStatusOrdersId getId() {
        return this.id;
    }
    
    public void setId(OrdersStatusOrdersId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="orders_id", nullable=false, insertable=false, updatable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OrdersStatus_id", nullable=false, insertable=false, updatable=false)
    public OrdersStatus getOrdersStatus() {
        return this.ordersStatus;
    }
    
    public void setOrdersStatus(OrdersStatus ordersStatus) {
        this.ordersStatus = ordersStatus;
    }




}


