package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrdersStatus generated by hbm2java
 */
@Entity
@Table(name="orders_status")
public class OrdersStatus  implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long id;
     private Date createDate;
     private String createUser;
     private String statusName;
     private Date updateDate;
     private List<OrdersOrdersStatus> ordersOrdersStatuses = new ArrayList<OrdersOrdersStatus>(0);
     private List<OrdersStatusOrders> ordersStatusOrderses = new ArrayList<OrdersStatusOrders>(0);

    public OrdersStatus() {
    }

	
    public OrdersStatus(long id) {
        this.id = id;
    }
    public OrdersStatus(long id, Date createDate, String createUser, String statusName, Date updateDate, List<OrdersOrdersStatus> ordersOrdersStatuses, List<OrdersStatusOrders> ordersStatusOrderses) {
       this.id = id;
       this.createDate = createDate;
       this.createUser = createUser;
       this.statusName = statusName;
       this.updateDate = updateDate;
       this.ordersOrdersStatuses = ordersOrdersStatuses;
       this.ordersStatusOrderses = ordersStatusOrderses;
    }
   
    @TableGenerator(
            name="SSMGen", 
            table="ID_GEN", 
            pkColumnName="GEN_KEY", 
            valueColumnName="GEN_VALUE", 
            pkColumnValue="ORDERSTATUS_ID", 
            allocationSize=1)
    @Id 
    @Column(name="id")
    @GeneratedValue(strategy=GenerationType.TABLE, generator="SSMGen")
    public long getId() {
        return this.id;
    }
    
    public void ListId(long id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void ListCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="create_user")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void ListCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="status_name")
    public String getStatusName() {
        return this.statusName;
    }
    
    public void ListStatusName(String statusName) {
        this.statusName = statusName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void ListUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ordersStatus")
    public List<OrdersOrdersStatus> getOrdersOrdersStatuses() {
        return this.ordersOrdersStatuses;
    }
    
    public void ListOrdersOrdersStatuses(List<OrdersOrdersStatus> ordersOrdersStatuses) {
        this.ordersOrdersStatuses = ordersOrdersStatuses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ordersStatus")
    public List<OrdersStatusOrders> getOrdersStatusOrderses() {
        return this.ordersStatusOrderses;
    }
    
    public void ListOrdersStatusOrderses(List<OrdersStatusOrders> ordersStatusOrderses) {
        this.ordersStatusOrderses = ordersStatusOrderses;
    }


	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}


	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}


	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}


	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}


	public void setOrdersOrdersStatuses(List<OrdersOrdersStatus> ordersOrdersStatuses) {
		this.ordersOrdersStatuses = ordersOrdersStatuses;
	}


	public void setOrdersStatusOrderses(List<OrdersStatusOrders> ordersStatusOrderses) {
		this.ordersStatusOrderses = ordersStatusOrderses;
	}


	public void setId(long id) {
		this.id = id;
	}




}


