package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrdersTaxStatus generated by hbm2java
 */
@Entity
@Table(name="orders_tax_status")
public class OrdersTaxStatus  implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long id;
     private Orders orders;
     private Date createDate;
     private String createUser;
     private String taxStatusName;
     private Date updateDate;
     private Set<Orders> orderses = new HashSet<Orders>(0);

    public OrdersTaxStatus() {
    }

	
    public OrdersTaxStatus(long id) {
        this.id = id;
    }
    public OrdersTaxStatus(long id, Orders orders, Date createDate, String createUser, String taxStatusName, Date updateDate, Set<Orders> orderses) {
       this.id = id;
       this.orders = orders;
       this.createDate = createDate;
       this.createUser = createUser;
       this.taxStatusName = taxStatusName;
       this.updateDate = updateDate;
       this.orderses = orderses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id")
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="create_user")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="tax_status_name")
    public String getTaxStatusName() {
        return this.taxStatusName;
    }
    
    public void setTaxStatusName(String taxStatusName) {
        this.taxStatusName = taxStatusName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ordersTaxStatus")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }




}


