package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders"
    ,catalog="ssm_test"
)
public class Orders  implements java.io.Serializable {


     private long id;
     private Customer customer;
     private Employees employees;
     private OrdersTaxStatus ordersTaxStatus;
     private Shippers shippers;
     private Date createDate;
     private String createUser;
     private Long currentStatus;
     private String notes;
     private Date orderDate;
     private Date paidDate;
     private String paymentType;
     private String qty;
     private String recipe;
     private String shipAddress;
     private String shipCity;
     private String shipCountryRegion;
     private String shipName;
     private String shipStateProvince;
     private String shipZipPostalCode;
     private Date shippedDate;
     private BigDecimal shippingFee;
     private Double taxRate;
     private BigDecimal taxes;
     private Date updateDate;
     private Set xtblDockets = new HashSet(0);
     private Set inventoryTransactionses = new HashSet(0);
     private Set ordersOrdersStatuses = new HashSet(0);
     private Set orderDetailses = new HashSet(0);
     private Set ordersStatusOrderses = new HashSet(0);
     private Set invoiceses = new HashSet(0);
     private Set ordersTaxStatuses = new HashSet(0);

    public Orders() {
    }

	
    public Orders(long id) {
        this.id = id;
    }
    public Orders(long id, Customer customer, Employees employees, OrdersTaxStatus ordersTaxStatus, Shippers shippers, Date createDate, String createUser, Long currentStatus, String notes, Date orderDate, Date paidDate, String paymentType, String qty, String recipe, String shipAddress, String shipCity, String shipCountryRegion, String shipName, String shipStateProvince, String shipZipPostalCode, Date shippedDate, BigDecimal shippingFee, Double taxRate, BigDecimal taxes, Date updateDate, Set xtblDockets, Set inventoryTransactionses, Set ordersOrdersStatuses, Set orderDetailses, Set ordersStatusOrderses, Set invoiceses, Set ordersTaxStatuses) {
       this.id = id;
       this.customer = customer;
       this.employees = employees;
       this.ordersTaxStatus = ordersTaxStatus;
       this.shippers = shippers;
       this.createDate = createDate;
       this.createUser = createUser;
       this.currentStatus = currentStatus;
       this.notes = notes;
       this.orderDate = orderDate;
       this.paidDate = paidDate;
       this.paymentType = paymentType;
       this.qty = qty;
       this.recipe = recipe;
       this.shipAddress = shipAddress;
       this.shipCity = shipCity;
       this.shipCountryRegion = shipCountryRegion;
       this.shipName = shipName;
       this.shipStateProvince = shipStateProvince;
       this.shipZipPostalCode = shipZipPostalCode;
       this.shippedDate = shippedDate;
       this.shippingFee = shippingFee;
       this.taxRate = taxRate;
       this.taxes = taxes;
       this.updateDate = updateDate;
       this.xtblDockets = xtblDockets;
       this.inventoryTransactionses = inventoryTransactionses;
       this.ordersOrdersStatuses = ordersOrdersStatuses;
       this.orderDetailses = orderDetailses;
       this.ordersStatusOrderses = ordersStatusOrderses;
       this.invoiceses = invoiceses;
       this.ordersTaxStatuses = ordersTaxStatuses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id")
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id")
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tax_status_id")
    public OrdersTaxStatus getOrdersTaxStatus() {
        return this.ordersTaxStatus;
    }
    
    public void setOrdersTaxStatus(OrdersTaxStatus ordersTaxStatus) {
        this.ordersTaxStatus = ordersTaxStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="shipper_id")
    public Shippers getShippers() {
        return this.shippers;
    }
    
    public void setShippers(Shippers shippers) {
        this.shippers = shippers;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="create_user")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="current_status")
    public Long getCurrentStatus() {
        return this.currentStatus;
    }
    
    public void setCurrentStatus(Long currentStatus) {
        this.currentStatus = currentStatus;
    }

    
    @Column(name="notes")
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="order_date", length=19)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="paid_date", length=19)
    public Date getPaidDate() {
        return this.paidDate;
    }
    
    public void setPaidDate(Date paidDate) {
        this.paidDate = paidDate;
    }

    
    @Column(name="payment_type")
    public String getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    
    @Column(name="qty")
    public String getQty() {
        return this.qty;
    }
    
    public void setQty(String qty) {
        this.qty = qty;
    }

    
    @Column(name="recipe")
    public String getRecipe() {
        return this.recipe;
    }
    
    public void setRecipe(String recipe) {
        this.recipe = recipe;
    }

    
    @Column(name="ship_address")
    public String getShipAddress() {
        return this.shipAddress;
    }
    
    public void setShipAddress(String shipAddress) {
        this.shipAddress = shipAddress;
    }

    
    @Column(name="ship_city")
    public String getShipCity() {
        return this.shipCity;
    }
    
    public void setShipCity(String shipCity) {
        this.shipCity = shipCity;
    }

    
    @Column(name="ship_country_region")
    public String getShipCountryRegion() {
        return this.shipCountryRegion;
    }
    
    public void setShipCountryRegion(String shipCountryRegion) {
        this.shipCountryRegion = shipCountryRegion;
    }

    
    @Column(name="ship_name")
    public String getShipName() {
        return this.shipName;
    }
    
    public void setShipName(String shipName) {
        this.shipName = shipName;
    }

    
    @Column(name="ship_state_province")
    public String getShipStateProvince() {
        return this.shipStateProvince;
    }
    
    public void setShipStateProvince(String shipStateProvince) {
        this.shipStateProvince = shipStateProvince;
    }

    
    @Column(name="ship_zip_postal_code")
    public String getShipZipPostalCode() {
        return this.shipZipPostalCode;
    }
    
    public void setShipZipPostalCode(String shipZipPostalCode) {
        this.shipZipPostalCode = shipZipPostalCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="shipped_date", length=19)
    public Date getShippedDate() {
        return this.shippedDate;
    }
    
    public void setShippedDate(Date shippedDate) {
        this.shippedDate = shippedDate;
    }

    
    @Column(name="shipping_fee")
    public BigDecimal getShippingFee() {
        return this.shippingFee;
    }
    
    public void setShippingFee(BigDecimal shippingFee) {
        this.shippingFee = shippingFee;
    }

    
    @Column(name="tax_rate", precision=22, scale=0)
    public Double getTaxRate() {
        return this.taxRate;
    }
    
    public void setTaxRate(Double taxRate) {
        this.taxRate = taxRate;
    }

    
    @Column(name="taxes")
    public BigDecimal getTaxes() {
        return this.taxes;
    }
    
    public void setTaxes(BigDecimal taxes) {
        this.taxes = taxes;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set getXtblDockets() {
        return this.xtblDockets;
    }
    
    public void setXtblDockets(Set xtblDockets) {
        this.xtblDockets = xtblDockets;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set getInventoryTransactionses() {
        return this.inventoryTransactionses;
    }
    
    public void setInventoryTransactionses(Set inventoryTransactionses) {
        this.inventoryTransactionses = inventoryTransactionses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set getOrdersOrdersStatuses() {
        return this.ordersOrdersStatuses;
    }
    
    public void setOrdersOrdersStatuses(Set ordersOrdersStatuses) {
        this.ordersOrdersStatuses = ordersOrdersStatuses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set orderDetailses) {
        this.orderDetailses = orderDetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set getOrdersStatusOrderses() {
        return this.ordersStatusOrderses;
    }
    
    public void setOrdersStatusOrderses(Set ordersStatusOrderses) {
        this.ordersStatusOrderses = ordersStatusOrderses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set getInvoiceses() {
        return this.invoiceses;
    }
    
    public void setInvoiceses(Set invoiceses) {
        this.invoiceses = invoiceses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set getOrdersTaxStatuses() {
        return this.ordersTaxStatuses;
    }
    
    public void setOrdersTaxStatuses(Set ordersTaxStatuses) {
        this.ordersTaxStatuses = ordersTaxStatuses;
    }




}


