package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrdersOrdersStatusId generated by hbm2java
 */
@Embeddable
public class OrdersOrdersStatusId  implements java.io.Serializable {


     private long orderId;
     private long orderStatussId;

    public OrdersOrdersStatusId() {
    }

    public OrdersOrdersStatusId(long orderId, long orderStatussId) {
       this.orderId = orderId;
       this.orderStatussId = orderStatussId;
    }
   


    @Column(name="Order_id", nullable=false)
    public long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(long orderId) {
        this.orderId = orderId;
    }


    @Column(name="orderStatuss_id", nullable=false)
    public long getOrderStatussId() {
        return this.orderStatussId;
    }
    
    public void setOrderStatussId(long orderStatussId) {
        this.orderStatussId = orderStatussId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdersOrdersStatusId) ) return false;
		 OrdersOrdersStatusId castOther = ( OrdersOrdersStatusId ) other; 
         
		 return (this.getOrderId()==castOther.getOrderId())
 && (this.getOrderStatussId()==castOther.getOrderStatussId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getOrderId();
         result = 37 * result + (int) this.getOrderStatussId();
         return result;
   }   


}


