package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Privileges generated by hbm2java
 */
@Entity
@Table(name="privileges"
    ,catalog="ssm_test"
)
public class Privileges  implements java.io.Serializable {


     private long id;
     private Date createDate;
     private String createUser;
     private String privilegeName;
     private String renderedDelete;
     private Date updateDate;
     private Set employeeses = new HashSet(0);

    public Privileges() {
    }

	
    public Privileges(long id) {
        this.id = id;
    }
    public Privileges(long id, Date createDate, String createUser, String privilegeName, String renderedDelete, Date updateDate, Set employeeses) {
       this.id = id;
       this.createDate = createDate;
       this.createUser = createUser;
       this.privilegeName = privilegeName;
       this.renderedDelete = renderedDelete;
       this.updateDate = updateDate;
       this.employeeses = employeeses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="create_user")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="privilege_name")
    public String getPrivilegeName() {
        return this.privilegeName;
    }
    
    public void setPrivilegeName(String privilegeName) {
        this.privilegeName = privilegeName;
    }

    
    @Column(name="renderedDelete")
    public String getRenderedDelete() {
        return this.renderedDelete;
    }
    
    public void setRenderedDelete(String renderedDelete) {
        this.renderedDelete = renderedDelete;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="privileges")
    public Set getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }




}


