package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchaseOrders generated by hbm2java
 */
@Entity
@Table(name="purchase_orders")
public class PurchaseOrders  implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long id;
     private Employees employees;
     private PurchaseOrderStatus purchaseOrderStatus;
     private Suppliers suppliers;
     private Integer approvedBy;
     private Date approvedDate;
     private Date createDate;
     private String createUser;
     private Date creationDate;
     private Date expectedDate;
     private String notes;
     private BigDecimal paymentAmount;
     private Date paymentDate;
     private String paymentMethod;
     private BigDecimal shippingFee;
     private Integer submittedBy;
     private Date submittedDate;
     private BigDecimal taxes;
     private Date updateDate;
     private List<InventoryTransactions> inventoryTransactionses = new ArrayList<InventoryTransactions>(0);
     private List<PurchaseOrderDetails> purchaseOrderDetailses = new ArrayList<PurchaseOrderDetails>(0);

    public PurchaseOrders() {
    }

	
    public PurchaseOrders(long id) {
        this.id = id;
    }
    public PurchaseOrders(long id, Employees employees, PurchaseOrderStatus purchaseOrderStatus, Suppliers suppliers, Integer approvedBy, Date approvedDate, Date createDate, String createUser, Date creationDate, Date expectedDate, String notes, BigDecimal paymentAmount, Date paymentDate, String paymentMethod, BigDecimal shippingFee, Integer submittedBy, Date submittedDate, BigDecimal taxes, Date updateDate, List<InventoryTransactions> inventoryTransactionses, List<PurchaseOrderDetails> purchaseOrderDetailses) {
       this.id = id;
       this.employees = employees;
       this.purchaseOrderStatus = purchaseOrderStatus;
       this.suppliers = suppliers;
       this.approvedBy = approvedBy;
       this.approvedDate = approvedDate;
       this.createDate = createDate;
       this.createUser = createUser;
       this.creationDate = creationDate;
       this.expectedDate = expectedDate;
       this.notes = notes;
       this.paymentAmount = paymentAmount;
       this.paymentDate = paymentDate;
       this.paymentMethod = paymentMethod;
       this.shippingFee = shippingFee;
       this.submittedBy = submittedBy;
       this.submittedDate = submittedDate;
       this.taxes = taxes;
       this.updateDate = updateDate;
       this.inventoryTransactionses = inventoryTransactionses;
       this.purchaseOrderDetailses = purchaseOrderDetailses;
    }
   
    @TableGenerator(
            name="SSMGen", 
            table="ID_GEN", 
            pkColumnName="GEN_KEY", 
            valueColumnName="GEN_VALUE", 
            pkColumnValue="PURCHESEORDER_ID", 
            allocationSize=1)
    @Id 
    @Column(name="id")
    @GeneratedValue(strategy=GenerationType.TABLE, generator="SSMGen")
    public long getId() {
        return this.id;
    }
    
    public void ListId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="created_by")
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void ListEmployees(Employees employees) {
        this.employees = employees;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status_id")
    public PurchaseOrderStatus getPurchaseOrderStatus() {
        return this.purchaseOrderStatus;
    }
    
    public void ListPurchaseOrderStatus(PurchaseOrderStatus purchaseOrderStatus) {
        this.purchaseOrderStatus = purchaseOrderStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="supplier_id")
    public Suppliers getSuppliers() {
        return this.suppliers;
    }
    
    public void ListSuppliers(Suppliers suppliers) {
        this.suppliers = suppliers;
    }

    
    @Column(name="approved_by")
    public Integer getApprovedBy() {
        return this.approvedBy;
    }
    
    public void ListApprovedBy(Integer approvedBy) {
        this.approvedBy = approvedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="approved_date", length=19)
    public Date getApprovedDate() {
        return this.approvedDate;
    }
    
    public void ListApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void ListCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="create_user")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void ListCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", length=19)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void ListCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expected_date", length=19)
    public Date getExpectedDate() {
        return this.expectedDate;
    }
    
    public void ListExpectedDate(Date expectedDate) {
        this.expectedDate = expectedDate;
    }

    
    @Column(name="notes")
    public String getNotes() {
        return this.notes;
    }
    
    public void ListNotes(String notes) {
        this.notes = notes;
    }

    
    @Column(name="payment_amount")
    public BigDecimal getPaymentAmount() {
        return this.paymentAmount;
    }
    
    public void ListPaymentAmount(BigDecimal paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="payment_date", length=19)
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void ListPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    
    @Column(name="payment_method")
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void ListPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    
    @Column(name="shipping_fee")
    public BigDecimal getShippingFee() {
        return this.shippingFee;
    }
    
    public void ListShippingFee(BigDecimal shippingFee) {
        this.shippingFee = shippingFee;
    }

    
    @Column(name="submitted_by")
    public Integer getSubmittedBy() {
        return this.submittedBy;
    }
    
    public void ListSubmittedBy(Integer submittedBy) {
        this.submittedBy = submittedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="submitted_date", length=19)
    public Date getSubmittedDate() {
        return this.submittedDate;
    }
    
    public void ListSubmittedDate(Date submittedDate) {
        this.submittedDate = submittedDate;
    }

    
    @Column(name="taxes")
    public BigDecimal getTaxes() {
        return this.taxes;
    }
    
    public void ListTaxes(BigDecimal taxes) {
        this.taxes = taxes;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void ListUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="purchaseOrders")
    public List<InventoryTransactions> getInventoryTransactionses() {
        return this.inventoryTransactionses;
    }
    
    public void ListInventoryTransactionses(List<InventoryTransactions> inventoryTransactionses) {
        this.inventoryTransactionses = inventoryTransactionses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="purchaseOrders")
    public List<PurchaseOrderDetails> getPurchaseOrderDetailses() {
        return this.purchaseOrderDetailses;
    }
    
    public void ListPurchaseOrderDetailses(List<PurchaseOrderDetails> purchaseOrderDetailses) {
        this.purchaseOrderDetailses = purchaseOrderDetailses;
    }


	public void setId(long id) {
		this.id = id;
	}


	public void setEmployees(Employees employees) {
		this.employees = employees;
	}


	public void setPurchaseOrderStatus(PurchaseOrderStatus purchaseOrderStatus) {
		this.purchaseOrderStatus = purchaseOrderStatus;
	}


	public void setSuppliers(Suppliers suppliers) {
		this.suppliers = suppliers;
	}


	public void setApprovedBy(Integer approvedBy) {
		this.approvedBy = approvedBy;
	}


	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}


	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}


	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}


	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}


	public void setExpectedDate(Date expectedDate) {
		this.expectedDate = expectedDate;
	}


	public void setNotes(String notes) {
		this.notes = notes;
	}


	public void setPaymentAmount(BigDecimal paymentAmount) {
		this.paymentAmount = paymentAmount;
	}


	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}


	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}


	public void setShippingFee(BigDecimal shippingFee) {
		this.shippingFee = shippingFee;
	}


	public void setSubmittedBy(Integer submittedBy) {
		this.submittedBy = submittedBy;
	}


	public void setSubmittedDate(Date submittedDate) {
		this.submittedDate = submittedDate;
	}


	public void setTaxes(BigDecimal taxes) {
		this.taxes = taxes;
	}


	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}


	public void setInventoryTransactionses(List<InventoryTransactions> inventoryTransactionses) {
		this.inventoryTransactionses = inventoryTransactionses;
	}


	public void setPurchaseOrderDetailses(List<PurchaseOrderDetails> purchaseOrderDetailses) {
		this.purchaseOrderDetailses = purchaseOrderDetailses;
	}
}


