package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchaseOrderStatus generated by hbm2java
 */
@Entity
@Table(name="purchase_order_status"
    ,catalog="ssm_test"
)
public class PurchaseOrderStatus  implements java.io.Serializable {


     private int id;
     private Date createDate;
     private String createUser;
     private String status;
     private Date updateDate;
     private Set purchaseOrderses = new HashSet(0);

    public PurchaseOrderStatus() {
    }

	
    public PurchaseOrderStatus(int id) {
        this.id = id;
    }
    public PurchaseOrderStatus(int id, Date createDate, String createUser, String status, Date updateDate, Set purchaseOrderses) {
       this.id = id;
       this.createDate = createDate;
       this.createUser = createUser;
       this.status = status;
       this.updateDate = updateDate;
       this.purchaseOrderses = purchaseOrderses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="create_user")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="status")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="purchaseOrderStatus")
    public Set getPurchaseOrderses() {
        return this.purchaseOrderses;
    }
    
    public void setPurchaseOrderses(Set purchaseOrderses) {
        this.purchaseOrderses = purchaseOrderses;
    }




}


