package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchaseOrders generated by hbm2java
 */
@Entity
@Table(name="purchase_orders"
    ,catalog="ssm_test"
)
public class PurchaseOrders  implements java.io.Serializable {


     private long id;
     private Employees employees;
     private PurchaseOrderStatus purchaseOrderStatus;
     private Suppliers suppliers;
     private Integer approvedBy;
     private Date approvedDate;
     private Date createDate;
     private String createUser;
     private Date creationDate;
     private Date expectedDate;
     private String notes;
     private BigDecimal paymentAmount;
     private Date paymentDate;
     private String paymentMethod;
     private BigDecimal shippingFee;
     private Integer submittedBy;
     private Date submittedDate;
     private BigDecimal taxes;
     private Date updateDate;
     private Set inventoryTransactionses = new HashSet(0);
     private Set purchaseOrderDetailses = new HashSet(0);

    public PurchaseOrders() {
    }

	
    public PurchaseOrders(long id) {
        this.id = id;
    }
    public PurchaseOrders(long id, Employees employees, PurchaseOrderStatus purchaseOrderStatus, Suppliers suppliers, Integer approvedBy, Date approvedDate, Date createDate, String createUser, Date creationDate, Date expectedDate, String notes, BigDecimal paymentAmount, Date paymentDate, String paymentMethod, BigDecimal shippingFee, Integer submittedBy, Date submittedDate, BigDecimal taxes, Date updateDate, Set inventoryTransactionses, Set purchaseOrderDetailses) {
       this.id = id;
       this.employees = employees;
       this.purchaseOrderStatus = purchaseOrderStatus;
       this.suppliers = suppliers;
       this.approvedBy = approvedBy;
       this.approvedDate = approvedDate;
       this.createDate = createDate;
       this.createUser = createUser;
       this.creationDate = creationDate;
       this.expectedDate = expectedDate;
       this.notes = notes;
       this.paymentAmount = paymentAmount;
       this.paymentDate = paymentDate;
       this.paymentMethod = paymentMethod;
       this.shippingFee = shippingFee;
       this.submittedBy = submittedBy;
       this.submittedDate = submittedDate;
       this.taxes = taxes;
       this.updateDate = updateDate;
       this.inventoryTransactionses = inventoryTransactionses;
       this.purchaseOrderDetailses = purchaseOrderDetailses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="created_by")
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status_id")
    public PurchaseOrderStatus getPurchaseOrderStatus() {
        return this.purchaseOrderStatus;
    }
    
    public void setPurchaseOrderStatus(PurchaseOrderStatus purchaseOrderStatus) {
        this.purchaseOrderStatus = purchaseOrderStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="supplier_id")
    public Suppliers getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Suppliers suppliers) {
        this.suppliers = suppliers;
    }

    
    @Column(name="approved_by")
    public Integer getApprovedBy() {
        return this.approvedBy;
    }
    
    public void setApprovedBy(Integer approvedBy) {
        this.approvedBy = approvedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="approved_date", length=19)
    public Date getApprovedDate() {
        return this.approvedDate;
    }
    
    public void setApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="create_user")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", length=19)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expected_date", length=19)
    public Date getExpectedDate() {
        return this.expectedDate;
    }
    
    public void setExpectedDate(Date expectedDate) {
        this.expectedDate = expectedDate;
    }

    
    @Column(name="notes")
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    
    @Column(name="payment_amount")
    public BigDecimal getPaymentAmount() {
        return this.paymentAmount;
    }
    
    public void setPaymentAmount(BigDecimal paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="payment_date", length=19)
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    
    @Column(name="payment_method")
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    
    @Column(name="shipping_fee")
    public BigDecimal getShippingFee() {
        return this.shippingFee;
    }
    
    public void setShippingFee(BigDecimal shippingFee) {
        this.shippingFee = shippingFee;
    }

    
    @Column(name="submitted_by")
    public Integer getSubmittedBy() {
        return this.submittedBy;
    }
    
    public void setSubmittedBy(Integer submittedBy) {
        this.submittedBy = submittedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="submitted_date", length=19)
    public Date getSubmittedDate() {
        return this.submittedDate;
    }
    
    public void setSubmittedDate(Date submittedDate) {
        this.submittedDate = submittedDate;
    }

    
    @Column(name="taxes")
    public BigDecimal getTaxes() {
        return this.taxes;
    }
    
    public void setTaxes(BigDecimal taxes) {
        this.taxes = taxes;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="purchaseOrders")
    public Set getInventoryTransactionses() {
        return this.inventoryTransactionses;
    }
    
    public void setInventoryTransactionses(Set inventoryTransactionses) {
        this.inventoryTransactionses = inventoryTransactionses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="purchaseOrders")
    public Set getPurchaseOrderDetailses() {
        return this.purchaseOrderDetailses;
    }
    
    public void setPurchaseOrderDetailses(Set purchaseOrderDetailses) {
        this.purchaseOrderDetailses = purchaseOrderDetailses;
    }




}


