package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchaseOrderDetails generated by hbm2java
 */
@Entity
@Table(name="purchase_order_details")
public class PurchaseOrderDetails  implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long id;
     private InventoryTransactions inventoryTransactions;
     private Products products;
     private PurchaseOrders purchaseOrders;
     private Date createDate;
     private String createUser;
     private Date dateReceived;
     private String postedToInventory;
     private BigDecimal quantity;
     private BigDecimal unitCost;
     private Date updateDate;

    public PurchaseOrderDetails() {
    }

	
    public PurchaseOrderDetails(long id) {
        this.id = id;
    }
    public PurchaseOrderDetails(long id, InventoryTransactions inventoryTransactions, Products products, PurchaseOrders purchaseOrders, Date createDate, String createUser, Date dateReceived, String postedToInventory, BigDecimal quantity, BigDecimal unitCost, Date updateDate) {
       this.id = id;
       this.inventoryTransactions = inventoryTransactions;
       this.products = products;
       this.purchaseOrders = purchaseOrders;
       this.createDate = createDate;
       this.createUser = createUser;
       this.dateReceived = dateReceived;
       this.postedToInventory = postedToInventory;
       this.quantity = quantity;
       this.unitCost = unitCost;
       this.updateDate = updateDate;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="inventory_id")
    public InventoryTransactions getInventoryTransactions() {
        return this.inventoryTransactions;
    }
    
    public void setInventoryTransactions(InventoryTransactions inventoryTransactions) {
        this.inventoryTransactions = inventoryTransactions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id")
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="purchase_order_id")
    public PurchaseOrders getPurchaseOrders() {
        return this.purchaseOrders;
    }
    
    public void setPurchaseOrders(PurchaseOrders purchaseOrders) {
        this.purchaseOrders = purchaseOrders;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="create_user")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_received", length=19)
    public Date getDateReceived() {
        return this.dateReceived;
    }
    
    public void setDateReceived(Date dateReceived) {
        this.dateReceived = dateReceived;
    }

    
    @Column(name="posted_to_inventory")
    public String getPostedToInventory() {
        return this.postedToInventory;
    }
    
    public void setPostedToInventory(String postedToInventory) {
        this.postedToInventory = postedToInventory;
    }

    
    @Column(name="quantity")
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="unit_cost")
    public BigDecimal getUnitCost() {
        return this.unitCost;
    }
    
    public void setUnitCost(BigDecimal unitCost) {
        this.unitCost = unitCost;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


