package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Shippers generated by hbm2java
 */
@Entity
@Table(name="shippers")
public class Shippers  implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long id;
     private String address;
     private String attachments;
     private String businessPhone;
     private String city;
     private String company;
     private String countryRegion;
     private Date createDate;
     private String createUser;
     private String emailAddress;
     private String faxNumber;
     private String firstName;
     private String homePhone;
     private String jobTitle;
     private String lastName;
     private String mobilePhone;
     private String notes;
     private String stateProvince;
     private Date updateDate;
     private String webPage;
     private String zipPostalCode;
     private Set<Orders> orderses = new HashSet<Orders>(0);

    public Shippers() {
    }

	
    public Shippers(long id) {
        this.id = id;
    }
    public Shippers(long id, String address, String attachments, String businessPhone, String city, String company, String countryRegion, Date createDate, String createUser, String emailAddress, String faxNumber, String firstName, String homePhone, String jobTitle, String lastName, String mobilePhone, String notes, String stateProvince, Date updateDate, String webPage, String zipPostalCode, Set<Orders> orderses) {
       this.id = id;
       this.address = address;
       this.attachments = attachments;
       this.businessPhone = businessPhone;
       this.city = city;
       this.company = company;
       this.countryRegion = countryRegion;
       this.createDate = createDate;
       this.createUser = createUser;
       this.emailAddress = emailAddress;
       this.faxNumber = faxNumber;
       this.firstName = firstName;
       this.homePhone = homePhone;
       this.jobTitle = jobTitle;
       this.lastName = lastName;
       this.mobilePhone = mobilePhone;
       this.notes = notes;
       this.stateProvince = stateProvince;
       this.updateDate = updateDate;
       this.webPage = webPage;
       this.zipPostalCode = zipPostalCode;
       this.orderses = orderses;
    }
   
    @TableGenerator(
            name="SSMGen", 
            table="ID_GEN", 
            pkColumnName="GEN_KEY", 
            valueColumnName="GEN_VALUE", 
            pkColumnValue="SHIPPER_ID", 
            allocationSize=1)
    @Id 
    @Column(name="id")
    @GeneratedValue(strategy=GenerationType.TABLE, generator="SSMGen")
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="attachments")
    public String getAttachments() {
        return this.attachments;
    }
    
    public void setAttachments(String attachments) {
        this.attachments = attachments;
    }

    
    @Column(name="business_phone")
    public String getBusinessPhone() {
        return this.businessPhone;
    }
    
    public void setBusinessPhone(String businessPhone) {
        this.businessPhone = businessPhone;
    }

    
    @Column(name="city")
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="company")
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }

    
    @Column(name="country_region")
    public String getCountryRegion() {
        return this.countryRegion;
    }
    
    public void setCountryRegion(String countryRegion) {
        this.countryRegion = countryRegion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="create_user")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="email_address")
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    
    @Column(name="fax_number")
    public String getFaxNumber() {
        return this.faxNumber;
    }
    
    public void setFaxNumber(String faxNumber) {
        this.faxNumber = faxNumber;
    }

    
    @Column(name="first_name")
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="home_phone")
    public String getHomePhone() {
        return this.homePhone;
    }
    
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }

    
    @Column(name="job_title")
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    
    @Column(name="last_name")
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="mobile_phone")
    public String getMobilePhone() {
        return this.mobilePhone;
    }
    
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    
    @Column(name="notes")
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    
    @Column(name="state_province")
    public String getStateProvince() {
        return this.stateProvince;
    }
    
    public void setStateProvince(String stateProvince) {
        this.stateProvince = stateProvince;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="web_page")
    public String getWebPage() {
        return this.webPage;
    }
    
    public void setWebPage(String webPage) {
        this.webPage = webPage;
    }

    
    @Column(name="zip_postal_code")
    public String getZipPostalCode() {
        return this.zipPostalCode;
    }
    
    public void setZipPostalCode(String zipPostalCode) {
        this.zipPostalCode = zipPostalCode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shippers")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }




}


