package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Strings generated by hbm2java
 */
@Entity
@Table(name="strings")
public class Strings  implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long stringId;
     private Date createDate;
     private String createUser;
     private String stringData;
     private Date updateDate;

    public Strings() {
    }

	
    public Strings(long stringId) {
        this.stringId = stringId;
    }
    public Strings(long stringId, Date createDate, String createUser, String stringData, Date updateDate) {
       this.stringId = stringId;
       this.createDate = createDate;
       this.createUser = createUser;
       this.stringData = stringData;
       this.updateDate = updateDate;
    }
   
     @Id 

    
    @Column(name="string_id", unique=true, nullable=false)
    public long getStringId() {
        return this.stringId;
    }
    
    public void setStringId(long stringId) {
        this.stringId = stringId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="create_user")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="string_data")
    public String getStringData() {
        return this.stringData;
    }
    
    public void setStringData(String stringData) {
        this.stringData = stringData;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


