package toto.ssm.entity;
// Generated May 7, 2020 10:21:16 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * XtblDocket generated by hbm2java
 */
@Entity
@Table(name="xtbl_docket"
    ,catalog="ssm_test"
)
public class XtblDocket  implements java.io.Serializable {


     private long id;
     private Orders orders;
     private String admix1ap;
     private String admix2ap;
     private String admix3ap;
     private String admix4ap;
     private String agg1mix;
     private String agg1sp;
     private String agg2mix;
     private String agg2sp;
     private String agg3mix;
     private String agg3sp;
     private String agg4mix;
     private String agg4sp;
     private String cemt1mix;
     private String cemt1sp;
     private String cemt2mix;
     private String cemt2sp;
     private String cemt3mix;
     private String cemt3sp;
     private String cemt4mix;
     private String cemt4sp;
     private String countdoc;
     private String dptype;
     private String datebatch;
     private String docketno;
     private String docketref;
     private String driver;
     private String finished;
     private String fuel;
     private String moist1;
     private String moist2;
     private String moist3;
     private String moist4;
     private String price;
     private String qf;
     private String qn;
     private String qtybatch;
     private String qtydocket;
     private String qtynet;
     private String qtyperbatch;
     private String qtytruck;
     private String qw;
     private String remark;
     private String status;
     private String temp0;
     private String temp1;
     private Date timeEx;
     private Date timeLoad;
     private String totalcost;
     private String uploaded;
     private String vat;
     private String wc;
     private String watersp;
     private Date createDate;
     private String createUser;
     private Date updateDate;

    public XtblDocket() {
    }

	
    public XtblDocket(long id) {
        this.id = id;
    }
    public XtblDocket(long id, Orders orders, String admix1ap, String admix2ap, String admix3ap, String admix4ap, String agg1mix, String agg1sp, String agg2mix, String agg2sp, String agg3mix, String agg3sp, String agg4mix, String agg4sp, String cemt1mix, String cemt1sp, String cemt2mix, String cemt2sp, String cemt3mix, String cemt3sp, String cemt4mix, String cemt4sp, String countdoc, String dptype, String datebatch, String docketno, String docketref, String driver, String finished, String fuel, String moist1, String moist2, String moist3, String moist4, String price, String qf, String qn, String qtybatch, String qtydocket, String qtynet, String qtyperbatch, String qtytruck, String qw, String remark, String status, String temp0, String temp1, Date timeEx, Date timeLoad, String totalcost, String uploaded, String vat, String wc, String watersp, Date createDate, String createUser, Date updateDate) {
       this.id = id;
       this.orders = orders;
       this.admix1ap = admix1ap;
       this.admix2ap = admix2ap;
       this.admix3ap = admix3ap;
       this.admix4ap = admix4ap;
       this.agg1mix = agg1mix;
       this.agg1sp = agg1sp;
       this.agg2mix = agg2mix;
       this.agg2sp = agg2sp;
       this.agg3mix = agg3mix;
       this.agg3sp = agg3sp;
       this.agg4mix = agg4mix;
       this.agg4sp = agg4sp;
       this.cemt1mix = cemt1mix;
       this.cemt1sp = cemt1sp;
       this.cemt2mix = cemt2mix;
       this.cemt2sp = cemt2sp;
       this.cemt3mix = cemt3mix;
       this.cemt3sp = cemt3sp;
       this.cemt4mix = cemt4mix;
       this.cemt4sp = cemt4sp;
       this.countdoc = countdoc;
       this.dptype = dptype;
       this.datebatch = datebatch;
       this.docketno = docketno;
       this.docketref = docketref;
       this.driver = driver;
       this.finished = finished;
       this.fuel = fuel;
       this.moist1 = moist1;
       this.moist2 = moist2;
       this.moist3 = moist3;
       this.moist4 = moist4;
       this.price = price;
       this.qf = qf;
       this.qn = qn;
       this.qtybatch = qtybatch;
       this.qtydocket = qtydocket;
       this.qtynet = qtynet;
       this.qtyperbatch = qtyperbatch;
       this.qtytruck = qtytruck;
       this.qw = qw;
       this.remark = remark;
       this.status = status;
       this.temp0 = temp0;
       this.temp1 = temp1;
       this.timeEx = timeEx;
       this.timeLoad = timeLoad;
       this.totalcost = totalcost;
       this.uploaded = uploaded;
       this.vat = vat;
       this.wc = wc;
       this.watersp = watersp;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id")
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    
    @Column(name="admix1ap", length=45)
    public String getAdmix1ap() {
        return this.admix1ap;
    }
    
    public void setAdmix1ap(String admix1ap) {
        this.admix1ap = admix1ap;
    }

    
    @Column(name="admix2ap", length=45)
    public String getAdmix2ap() {
        return this.admix2ap;
    }
    
    public void setAdmix2ap(String admix2ap) {
        this.admix2ap = admix2ap;
    }

    
    @Column(name="admix3ap", length=45)
    public String getAdmix3ap() {
        return this.admix3ap;
    }
    
    public void setAdmix3ap(String admix3ap) {
        this.admix3ap = admix3ap;
    }

    
    @Column(name="admix4ap", length=45)
    public String getAdmix4ap() {
        return this.admix4ap;
    }
    
    public void setAdmix4ap(String admix4ap) {
        this.admix4ap = admix4ap;
    }

    
    @Column(name="agg1mix", length=45)
    public String getAgg1mix() {
        return this.agg1mix;
    }
    
    public void setAgg1mix(String agg1mix) {
        this.agg1mix = agg1mix;
    }

    
    @Column(name="agg1sp", length=45)
    public String getAgg1sp() {
        return this.agg1sp;
    }
    
    public void setAgg1sp(String agg1sp) {
        this.agg1sp = agg1sp;
    }

    
    @Column(name="agg2mix", length=45)
    public String getAgg2mix() {
        return this.agg2mix;
    }
    
    public void setAgg2mix(String agg2mix) {
        this.agg2mix = agg2mix;
    }

    
    @Column(name="agg2sp", length=45)
    public String getAgg2sp() {
        return this.agg2sp;
    }
    
    public void setAgg2sp(String agg2sp) {
        this.agg2sp = agg2sp;
    }

    
    @Column(name="agg3mix", length=45)
    public String getAgg3mix() {
        return this.agg3mix;
    }
    
    public void setAgg3mix(String agg3mix) {
        this.agg3mix = agg3mix;
    }

    
    @Column(name="agg3sp", length=45)
    public String getAgg3sp() {
        return this.agg3sp;
    }
    
    public void setAgg3sp(String agg3sp) {
        this.agg3sp = agg3sp;
    }

    
    @Column(name="agg4mix", length=45)
    public String getAgg4mix() {
        return this.agg4mix;
    }
    
    public void setAgg4mix(String agg4mix) {
        this.agg4mix = agg4mix;
    }

    
    @Column(name="agg4sp", length=45)
    public String getAgg4sp() {
        return this.agg4sp;
    }
    
    public void setAgg4sp(String agg4sp) {
        this.agg4sp = agg4sp;
    }

    
    @Column(name="cemt1mix", length=45)
    public String getCemt1mix() {
        return this.cemt1mix;
    }
    
    public void setCemt1mix(String cemt1mix) {
        this.cemt1mix = cemt1mix;
    }

    
    @Column(name="cemt1sp", length=45)
    public String getCemt1sp() {
        return this.cemt1sp;
    }
    
    public void setCemt1sp(String cemt1sp) {
        this.cemt1sp = cemt1sp;
    }

    
    @Column(name="cemt2mix", length=45)
    public String getCemt2mix() {
        return this.cemt2mix;
    }
    
    public void setCemt2mix(String cemt2mix) {
        this.cemt2mix = cemt2mix;
    }

    
    @Column(name="cemt2sp", length=45)
    public String getCemt2sp() {
        return this.cemt2sp;
    }
    
    public void setCemt2sp(String cemt2sp) {
        this.cemt2sp = cemt2sp;
    }

    
    @Column(name="cemt3mix", length=45)
    public String getCemt3mix() {
        return this.cemt3mix;
    }
    
    public void setCemt3mix(String cemt3mix) {
        this.cemt3mix = cemt3mix;
    }

    
    @Column(name="cemt3sp", length=45)
    public String getCemt3sp() {
        return this.cemt3sp;
    }
    
    public void setCemt3sp(String cemt3sp) {
        this.cemt3sp = cemt3sp;
    }

    
    @Column(name="cemt4mix", length=45)
    public String getCemt4mix() {
        return this.cemt4mix;
    }
    
    public void setCemt4mix(String cemt4mix) {
        this.cemt4mix = cemt4mix;
    }

    
    @Column(name="cemt4sp", length=45)
    public String getCemt4sp() {
        return this.cemt4sp;
    }
    
    public void setCemt4sp(String cemt4sp) {
        this.cemt4sp = cemt4sp;
    }

    
    @Column(name="countdoc", length=45)
    public String getCountdoc() {
        return this.countdoc;
    }
    
    public void setCountdoc(String countdoc) {
        this.countdoc = countdoc;
    }

    
    @Column(name="dptype", length=45)
    public String getDptype() {
        return this.dptype;
    }
    
    public void setDptype(String dptype) {
        this.dptype = dptype;
    }

    
    @Column(name="datebatch", length=45)
    public String getDatebatch() {
        return this.datebatch;
    }
    
    public void setDatebatch(String datebatch) {
        this.datebatch = datebatch;
    }

    
    @Column(name="docketno", length=45)
    public String getDocketno() {
        return this.docketno;
    }
    
    public void setDocketno(String docketno) {
        this.docketno = docketno;
    }

    
    @Column(name="docketref", length=45)
    public String getDocketref() {
        return this.docketref;
    }
    
    public void setDocketref(String docketref) {
        this.docketref = docketref;
    }

    
    @Column(name="driver", length=45)
    public String getDriver() {
        return this.driver;
    }
    
    public void setDriver(String driver) {
        this.driver = driver;
    }

    
    @Column(name="finished", length=45)
    public String getFinished() {
        return this.finished;
    }
    
    public void setFinished(String finished) {
        this.finished = finished;
    }

    
    @Column(name="fuel", length=45)
    public String getFuel() {
        return this.fuel;
    }
    
    public void setFuel(String fuel) {
        this.fuel = fuel;
    }

    
    @Column(name="moist1", length=45)
    public String getMoist1() {
        return this.moist1;
    }
    
    public void setMoist1(String moist1) {
        this.moist1 = moist1;
    }

    
    @Column(name="moist2", length=45)
    public String getMoist2() {
        return this.moist2;
    }
    
    public void setMoist2(String moist2) {
        this.moist2 = moist2;
    }

    
    @Column(name="moist3", length=45)
    public String getMoist3() {
        return this.moist3;
    }
    
    public void setMoist3(String moist3) {
        this.moist3 = moist3;
    }

    
    @Column(name="moist4", length=45)
    public String getMoist4() {
        return this.moist4;
    }
    
    public void setMoist4(String moist4) {
        this.moist4 = moist4;
    }

    
    @Column(name="price", length=45)
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }

    
    @Column(name="qf", length=45)
    public String getQf() {
        return this.qf;
    }
    
    public void setQf(String qf) {
        this.qf = qf;
    }

    
    @Column(name="qn", length=45)
    public String getQn() {
        return this.qn;
    }
    
    public void setQn(String qn) {
        this.qn = qn;
    }

    
    @Column(name="qtybatch", length=45)
    public String getQtybatch() {
        return this.qtybatch;
    }
    
    public void setQtybatch(String qtybatch) {
        this.qtybatch = qtybatch;
    }

    
    @Column(name="qtydocket", length=45)
    public String getQtydocket() {
        return this.qtydocket;
    }
    
    public void setQtydocket(String qtydocket) {
        this.qtydocket = qtydocket;
    }

    
    @Column(name="qtynet", length=45)
    public String getQtynet() {
        return this.qtynet;
    }
    
    public void setQtynet(String qtynet) {
        this.qtynet = qtynet;
    }

    
    @Column(name="qtyperbatch", length=45)
    public String getQtyperbatch() {
        return this.qtyperbatch;
    }
    
    public void setQtyperbatch(String qtyperbatch) {
        this.qtyperbatch = qtyperbatch;
    }

    
    @Column(name="qtytruck", length=45)
    public String getQtytruck() {
        return this.qtytruck;
    }
    
    public void setQtytruck(String qtytruck) {
        this.qtytruck = qtytruck;
    }

    
    @Column(name="qw", length=45)
    public String getQw() {
        return this.qw;
    }
    
    public void setQw(String qw) {
        this.qw = qw;
    }

    
    @Column(name="remark", length=45)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="temp0", length=45)
    public String getTemp0() {
        return this.temp0;
    }
    
    public void setTemp0(String temp0) {
        this.temp0 = temp0;
    }

    
    @Column(name="temp1", length=45)
    public String getTemp1() {
        return this.temp1;
    }
    
    public void setTemp1(String temp1) {
        this.temp1 = temp1;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_ex", length=19)
    public Date getTimeEx() {
        return this.timeEx;
    }
    
    public void setTimeEx(Date timeEx) {
        this.timeEx = timeEx;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_load", length=19)
    public Date getTimeLoad() {
        return this.timeLoad;
    }
    
    public void setTimeLoad(Date timeLoad) {
        this.timeLoad = timeLoad;
    }

    
    @Column(name="totalcost", length=45)
    public String getTotalcost() {
        return this.totalcost;
    }
    
    public void setTotalcost(String totalcost) {
        this.totalcost = totalcost;
    }

    
    @Column(name="uploaded", length=45)
    public String getUploaded() {
        return this.uploaded;
    }
    
    public void setUploaded(String uploaded) {
        this.uploaded = uploaded;
    }

    
    @Column(name="vat", length=45)
    public String getVat() {
        return this.vat;
    }
    
    public void setVat(String vat) {
        this.vat = vat;
    }

    
    @Column(name="wc", length=45)
    public String getWc() {
        return this.wc;
    }
    
    public void setWc(String wc) {
        this.wc = wc;
    }

    
    @Column(name="watersp", length=45)
    public String getWatersp() {
        return this.watersp;
    }
    
    public void setWatersp(String watersp) {
        this.watersp = watersp;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="create_user")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


